name: innovativeproject-loancalculator

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  #setup-backend-environment:
    #runs-on: ubuntu-latest

    #steps:
    #- uses: actions/checkout@v2

    #- name: Set up Python 3.9.10
    #  uses: actions/setup-python@v2
    #  with:
    #    python-version: "3.9.10"
    
    #- name: Install backend dependencies
    #  run: |
    #    curl -sSL https://install.python-poetry.org | python3 -
    #    poetry config virtualenvs.create false
    #    cd backend
    #    poetry install
    
  #lint-backend:
    #runs-on: ubuntu-latest
    
  #test-backend:
  
  
  setup-frontend-environment:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node 16.14.0
      uses: actions/setup-node@v2
      with:
        node-version: "16.14.0"
        cache: "npm"
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm ci

  lint-frontend:
    - name: Format and lint frontend with eslint and prettier
      needs: setup-frontend-environment
      run: |
        cd frontend
        npx prettier --write ./src
        npx eslint --fix ./src
  
  
  test-frontend:
    - name: Test frontend with npm test
      need: lint-frontend
      run: |
        cd frontend
        npm run build --if-present
        npm test
  
  #build:
    
  